import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-auto-generated',
  templateUrl: './auto-generated.component.html',
  styleUrls: ['./auto-generated.component.css'],
  moduleId: module.id
})
export class AutoGeneratedComponent implements OnInit {

  constructor() { }

    public progressValue: number;

    ngOnInit() {
        this.progressValue = 25;
    }


}
