import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
import { HttpClientModule } from '@angular/common/http';
import { AppRoutingModule } from '@src/app/app-routing.module';
import { AppComponent } from '@src/app/app.component';
import {FormsModule} from '@angular/forms';
import {MyvilleModule} from '@src/app/myville/myville.module';
import { VilleService } from '@src/app/ville.service';
import { PageNotFoundComponent } from '@src/app/page-not-found/page-not-found.component';
import { MeteoModule } from '@src/app/meteo/meteo.module';
import { AutoGeneratedComponent } from '@src/app/auto-generated/auto-generated.component';

 


@NgModule({
  declarations: [
    AppComponent,
    PageNotFoundComponent,
    AutoGeneratedComponent
  ],
  imports: [
    BrowserModule,
    HttpClientModule,
    MyvilleModule,
    MeteoModule,
    FormsModule,
    AppRoutingModule
    
  ],
  providers: [
    VilleService
  ],
  bootstrap: [AppComponent]
})
export class AppModule { }
